### ISSUE TITLE
install的时候报错

### ISSUE THREAD

**Issue by jimenbian** [douban/dpark#46]
Installed /Library/Python/2.7/site-packages/DPark-0.1-py2.7-macosx-10.8-intel.egg
Processing dependencies for DPark==0.1
error: Installed distribution protobuf 3.0.0-alpha-1 conflicts with requirement protobuf>=2.5.0,<3

protobuf有版本限制，找了一下应该是文件要求安装protobuf3.0以上版本，但是系统要求只能是2.5.0到3之间的版本。不知道怎么修改这个限制。谢谢

**Comment by windreamer** [comment]
fixed in 7b580ea
