### ISSUE TITLE
需要频繁的重复用到某个大的rdd进行计算,有什么好方法吗？

### ISSUE THREAD

**Issue by richard403** [douban/dpark#47]
如：
经过很多的中间计算得出一个较大的rdd,后面的运算需要重复的用到这个rdd,有什么好的建议吗？
用cache和snapshot都会出错
目前我自己是先把rdd用saveAsTextFile写文件，运算用到时再导入

**Comment by windreamer** [comment]
snapshot本来是用来处理这种情况的， 但是可能有不少bug，如果有具体出错的信息可以发上来我们看看应该怎么样

saveAsTextFile的workaround我们也经常用，希望能完善snapshot的方式来替代这种workaround...

**Comment by richard403** [comment]
<OtherFailure Traceback (most recent call last):
  File "/mfs/×/venv/lib/python2.7/site-packages/dpark/executor.py", line 59, in run_task
    result = task.run(ntry)
  File "/mfs/×/venv/lib/python2.7/site-packages/dpark/task.py", line 52, in run
    return self.func(self.rdd.iterator(self.split))
  File "/mfs/×/venv/lib/python2.7/site-packages/dpark/rdd.py", line 122, in iterator
    v = cPickle.loads(open(p).read())
EOFError
=============================================================================
 运行时一个task申请的内存不存时，需要kill，重新申请更大的内存时，会发生
手动指定足够大的内存，避免kill，貌似不会出现（尝试的次数较少）

**Comment by windreamer** [comment]
我们现在更新snapshot到checkpoint, 希望能解决你的问题
