### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by skymfc** [douban/dpark#54]
rhel7 3.10.0-229.el7.x86_64,
python 2.7.5
运行python setup.py install
出错：
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c dpark/portable_hash.c -o build/temp.linux-x86_64-2.7/dpark/portable_hash.o
dpark/portable_hash.c:8:22: 致命错误：pyconfig.h：没有那个文件或目录
 #include "pyconfig.h"

**Comment by skymfc** [comment]
PS:平台是64位的，查看了以下只有pyconfig-64.h

**Comment by windreamer** [comment]
hi @skymfc ,

DPark 内部有一个跨机器保持一致的hash实现，这个hash是C语言实现的，在编译这个组件的时候需要Python代码（至少需要头文件），所以请检查你的 /user/include/python2.7下是否有相应的文件，如果没有请尝试安装python-dev或之类的包来解决相关问题
