### ISSUE TITLE
dpark在mesos上安装部署

### ISSUE THREAD

**Issue by snowlord** [douban/dpark#55]
dpark怎样在mesos上安装部署?mesos怎么启动Myexecutor来运行task的?

**Comment by windreamer** [comment]
不好意思回复有点晚
1. 首先需要一个mesos集群环境，集群的搭建可以看mesos的文档：http://mesos.apache.org/gettingstarted/
1. 需要在用提交的机器，以及所有的slave机器上安装DPark
1. 确保所有slave和提交的机器上都有所需的账号，如果你使用moosfs或者其他网络共享文件系统，请保证所有机器的账号id相同，如果需要制定dpark的配置文件，请保证这些机器的/etc/dpark.conf有相同并且正确的配置
1. 执行你的DPark脚本，增加 -m <host>[:<port>] 的配置来指定 mesos master, 使用 -m mesos时，dpark会尝试使用 MESOS_MASTER 环境变量
1. 观察DPark脚本是不是在mesos执行成功

你也可以选择用Docker环境，做法类似，只是不再需要在各个slave上安装DPark，而是需要各个slave安装docker并配置mesos支持docker isolation，然后制作一个和提交环境相同的Docker Image, 在运行DPark脚本时用 -I 参数指定这个image，这样各个slave就会使用Docker Image里面的DPark环境。

**Comment by zengzhiming** [comment]
在mesos 上使用docker 的方式运行 dpark ，有没有部署的文档可以参考？
