### ISSUE TITLE
question about the testcases of countByValueAndWindow

### ISSUE THREAD

**Issue by krist-jin** [douban/dpark#56]
In the [test codes](https://github.com/douban/dpark/blob/master/tests/test_dstream.py#L324) about countByValueAndWindow, I found it's different from the [Spark's test cases](https://github.com/apache/spark/blob/master/python/pyspark/streaming/tests.py#L628).

The format and meaning of these two output (Dpark streaming and Spark streaming) are different. Although I think Dpark accords with the [documentation](http://spark.apache.org/docs/latest/streaming-programming-guide.html#window-operations):
When called on a DStream of (K, V) pairs, returns a new DStream of (K, Long) pairs where the value of each key is its frequency within a sliding window. Like in reduceByKeyAndWindow, the number of reduce tasks is configurable through an optional argument.

Could someone please explain this difference a little bit?

Please also refer to [this related question](http://stackoverflow.com/q/34114585/4698425) on stackoverflow.

Thanks!

**Comment by windreamer** [comment]
I think `countByKeyAndWindow` in DPark and `countByValueAndWindow` are different APIs.
In DPark, `countByKeyAndWindow` returns a stream of pairs within a sliding window, just as u mentioned, and this is confirmed by the testcase of DPark.
As in Spark, if I am not wrong, `countByValueAndWIndow` return a stream of integers **"contains the count of distinct elements"**, and this behavior can be comfirmed by the comment of Spark code: https://github.com/apache/spark/blob/master/python/pyspark/streaming/dstream.py#L483

So in fact they are two different API with similar names, and I believe Spark Streaming doc is probalbly outdated and misleading.

@davies can u help me to confirm this issue?

**Comment by krist-jin** [comment]
Thanks for the reply.
In that sense, it seems there are some inconsistency between PySpark and Scala-Spark over countByValue and countByValueAndWindow. 
PySpark returns the count of distinct elements, which is one single number. While Scala-Spark returns the count of **each** distinct elements, which is a list of (k,v) pairs where k is the element and v is the count. Personally I think the latter make more sense.
