### ISSUE TITLE
在mesos 上使用docker 的方式运行 dpark ，有没有部署的文档可以参考？

### ISSUE THREAD

**Issue by zengzhiming** [douban/dpark#57]
在mesos 上使用docker 的方式运行 dpark ，有没有部署的文档可以参考？

**Comment by windreamer** [comment]
1. mesos需要配置docker支持： http://mesos.apache.org/documentation/latest/docker-containerizer/
1. 一个docker image并上传到你的registry: 
    * 需要尽可能和你的提交环境一致
    * 安装同样版本的DPark及其依赖
    * 放入正确的`/etc/dpark.conf`
1. 在提交的时候 ‘-I’ 指定运行的docker url， ‘-V’ 指定运行时需要volume的路径， 具体见 http://mesos.apache.org/documentation/latest/docker-containerizer/
