### ISSUE TITLE
Translation Docs

### ISSUE THREAD

**Issue by delijati** [douban/dpark#59]
This Project looks promising but could someone translate the docs and add a architectural overview.

**Comment by windreamer** [comment]
yes, we need more documents in English.
in fact we are not native speaker in English so it seems a bit harder for us to write long paragraphs, and i have to admit i am lazy...

we will try to publish more documents, both in English and Chinese, if possible, in the near future. and i think u can write an issue when u need help, and we will try to respond asap.
