### ISSUE TITLE
python xy 安装错误怎么解决？

### ISSUE THREAD

**Issue by czly** [douban/dpark#60]
File "C:\Python27\lib\site-packages\Cython\Utils.py", line 22, in wrapper
   res = cache[args] = f(*args)
 File "C:\Python27\lib\site-packages\Cython\Utils.py", line 111, in search_incl
de_directories
   path = os.path.join(dir, dotted_filename)
 File "C:\Python27\lib\ntpath.py", line 85, in join
   result_path = result_path + p_path
nicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 1: ordinal
ot in range(128)
uilding 'dpark.portable_hash' extension
reating build\temp.win32-2.7
reating build\temp.win32-2.7\Release
reating build\temp.win32-2.7\Release\dpark
:\Program Files\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe
c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcd
ark\portable_hash.c /Fobuild\temp.win32-2.7\Release\dpark\portable_hash.obj
ortable_hash.c
park\portable_hash.c(1) : fatal error C1189: #error :  Do not use this file, it
is the result of a failed Cython compilation.
rror: command 'C:\Program Files\Common Files\Microsoft\Visual C++ for Pytho
\9.0\VC\Bin\cl.exe' failed with exit status 2

**Comment by windreamer** [comment]
hi @czly 目前dpark还不支持windows
