### ISSUE TITLE
Couldn't download the mesos.interface

### ISSUE THREAD

**Issue by alidisi** [douban/dpark#64]
Couldn't find a setup script in /tmp/easy_install-QfQ_64/mesos.interface-1.0.1.linux-x86_64.tar.gz

**Comment by windreamer** [comment]
It seems an issue of Mesos. You may try `pip install mesos.interface==0.27.1` first. And then install DPark again.

**Comment by alidisi** [comment]
it is the problem of the easy_install  and i use pip install  mesos.interface solve the problem by hand

**Comment by windreamer** [comment]
OK, close this issue then.
