### ISSUE TITLE
pymesos 0.1.6 VS mesosphere 1.1.0, 取不到 slave id 

### ISSUE THREAD

**Issue by cntaogong** [douban/dpark#66]
环境: pymesos 0.1.6, mesosphere 1.1.0 , dpark 0.3.5
文件: executor.py
函数: reply_status
问题: mesos_pb2.TaskStatus()返回的status对象的slave_id属性是空

def reply_status(driver, task_id, state, data=None):
    **status = mesos_pb2.TaskStatus()**
    status.task_id.MergeFrom(task_id)
    status.state = state
    status.timestamp = time.time()
    if data is not None:
        status.data = data
    driver.sendStatusUpdate(status)

**Comment by windreamer** [comment]
https://github.com/douban/pymesos/pull/45
