### ISSUE TITLE
DeprecationWarning: Call to deprecated function or method decompress (use lz4.block.decompress instead)

### ISSUE THREAD

**Issue by fhyme** [douban/dpark#70]
运行过程中会输出多行
DeprecationWarning: Call to deprecated function or method decompress (use lz4.block.decompress instead)

请问是什么原因

**Comment by windreamer** [comment]
DO NOT PANIC! :)

从 `lz4-0.9.0` 开始 `lz4.decompress` 不再建议使用了，这只是提醒，不会对现有的结果有任何影响
我们后续会把这个接口迁移完成。

**Comment by fhyme** [comment]
谢谢，但如何可以ignore这个warning，我用python -W ignore xxx.py并不起作用
