### ISSUE TITLE
通过textFile创建rdd时，如何给每一行文本添加一个行号？

### ISSUE THREAD

**Issue by fhyme** [douban/dpark#72]
通过textFile创建rdd，文件中的每一行是一个document，现在需要进行分词、转vector等，怎么样给每一行自动添加一个行号，跟其在text file中的对应行号一致

**Comment by zzl0** [comment]
@fhyme 你需要的是 [enumerate](https://github.com/douban/dpark/blob/master/dpark/rdd.py#L282) 吗？

```python
    def enumerate(self):
        """
        enumerate this RDD.
        >>> dpark.parallelize(["a", "b", "c", "d"], 3).enumerate().collect()
        [(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]
        """
```

**Comment by fhyme** [comment]
@zzl0 原来有enumerate，多谢多谢，没有注意到
