### ISSUE TITLE
pypy 启动报错

### ISSUE THREAD

**Issue by Err0rZero** [douban/dpark#78]
pypy 安装成功，但在import dpark的时候报错

root@test:/opt# pypy
Python 3.5.3 (3f6eaa010fce, Jan 11 2018, 04:44:35)
[PyPy 5.10.1 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> from dpark import DparkContext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'DparkContext'
>>>>

**Comment by windreamer** [comment]
Can you provide some more infomations?
For example, you may try this:
```python
import dpark
print(dpark.__path__)
print(dir(dpark))
```
```

**Comment by Err0rZero** [comment]
.. fix 
Not fully installed....
