### ISSUE TITLE
如何在windows环境下调试

### ISSUE THREAD

**Issue by viking714** [douban/dpark#89]
您好，我想学习一下dpark。我如果想在windows环境下用类似pycharm的ide去编辑和调试dpark，这个能给个方案么？万分感谢。我试着把req.txt里面的包安装了一下，但是一运行，就报错了（ModuleNotFoundError: No module named 'dpark.utils.crc32c'），我查看了一下是个c语言的文件没法识别。估计是缺少第三方的支持。再一次表示感谢。

**Comment by ariesdevil** [comment]
抱歉，目前不支持 Windows
